-- ============================================================================
-- Kratos Defense Intelligence Agent - Database and Schema Setup
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS KRATOS_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Create database
CREATE DATABASE IF NOT EXISTS KRATOS_INTELLIGENCE;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS KRATOS_INTELLIGENCE.RAW;
CREATE SCHEMA IF NOT EXISTS KRATOS_INTELLIGENCE.ANALYTICS;

-- Grant privileges
GRANT USAGE ON WAREHOUSE KRATOS_WH TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE KRATOS_INTELLIGENCE TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA KRATOS_INTELLIGENCE.RAW TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA KRATOS_INTELLIGENCE.ANALYTICS TO ROLE SYSADMIN;
GRANT ALL ON SCHEMA KRATOS_INTELLIGENCE.RAW TO ROLE SYSADMIN;
GRANT ALL ON SCHEMA KRATOS_INTELLIGENCE.ANALYTICS TO ROLE SYSADMIN;

SELECT 'Database and schemas created successfully' AS status;

